# Generated by Django 3.0.3 on 2020-05-17 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20200517_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 17, 10, 12, 56, 396859, tzinfo=utc)),
        ),
    ]
